version: '3.4'

services:
  ecommerce:
    image: ${DOCKER_REGISTRY-}ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    restart: always    
    networks:
      - postgresql
      - mongodb
      - elastic
      - api   
    depends_on:
      - pgbouncer
      - mongodb-primary
      - elasticsearch-master
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage            
      - TZ=Asia/Tehran
      - PGTZ=Asia/Tehran  
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
       interval: 10s
       retries: 10
       start_period: 5s
       timeout: 3s
    deploy: 
      replicas: 3

  ecommerce-nginx:
    image: bitnami/openresty:latest
    restart: on-failure   
    user: root
    ports: 
      - 8080:80
    networks:      
      - api
    volumes:       
      - "./nginx.conf:/etc/openresty/nginx.conf:ro"
    links:
      - ecommerce
    depends_on:
      - ecommerce
    environment:      
      - TZ=Asia/Tehran
      - PGTZ=Asia/Tehran    