version: '3.4'

networks:
  postgresql:
  mongodb:
  elastic:
  api: 

volumes:
  postgres-master-data:
    driver: local
  postgres-slave-data:
    driver: local
  mongodb-master-data:
    driver: local
  mongodb-slave-data:
    driver: local
  mongodb-arbiter-data:
    driver: local
  elasticsearch-master-data:
    driver: local
  elasticsearch-slave-data:
    driver: local

services:
  postgres-master:
    image: bitnami/postgresql:latest
    user: root
    restart: on-failure
    networks:
      - postgresql
    volumes:
       - postgres-master-data:/bitnami/postgresql        
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user_postgres
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password_P@ssW0rd
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=P@ssW0rd      
      - POSTGRESQL_DATABASE=ECommerce
      - ALLOW_EMPTY_PASSWORD=yes     
      - TZ=Asia/Tehran
      - PGTZ=Asia/Tehran    

  postgres-slave:
    image: bitnami/postgresql:latest
    user: root
    restart: on-failure      
    networks:
      - postgresql
    volumes:
       - postgres-slave-data:/bitnami/postgresql   
    depends_on:
      - postgres-master
    environment:      
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user_postgres
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password_P@ssW0rd
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_PASSWORD=P@ssW0rd      
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Tehran
      - PGTZ=Asia/Tehran     
    deploy: 
      replicas: 1

  pgbouncer:
    image: edoburu/pgbouncer:latest
    user: root
    restart: on-failure    
    networks:
      - postgresql
    ports:
      - 5432:5432
    depends_on:
      - postgres-master
      - postgres-slave
    environment:      
      - DB_USER=postgres
      - DB_PASSWORD=P@ssW0rd
      - DB_HOST=postgres-master
      - DB_NAME=ECommerce
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres
      - AUTH_TYPE=plain

  mongodb-master:
    image: bitnami/mongodb:latest
    restart: on-failure
    networks:
      - mongodb  
    ports:
      - 27017:27017
    volumes:
      - mongodb-master-data:/bitnami/mongodb 
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-master
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=repl_password_P@ssW0rd
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - TZ=Asia/Tehran
      - PGTZ=Asia/Tehran      

  mongodb-slave:
    image: bitnami/mongodb:latest    
    restart: on-failure
    networks:
      - mongodb
    depends_on:
      - mongodb-master
    volumes:
      - mongodb-slave-data:/bitnami/mongodb 
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-slave
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-master
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=repl_password_P@ssW0rd
      - MONGODB_REPLICA_SET_KEY=replicasetkey123      
      - TZ=Asia/Tehran
      - PGTZ=Asia/Tehran   
    deploy:
      replicas: 1

  mongodb-arbiter:
    image: bitnami/mongodb:latest    
    restart: on-failure
    networks:
      - mongodb
    depends_on:
      - mongodb-master
    volumes:
      - mongodb-arbiter-data:/bitnami/mongodb 
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-master
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=repl_password_P@ssW0rd
      - MONGODB_REPLICA_SET_KEY=replicasetkey123      
      - TZ=Asia/Tehran
      - PGTZ=Asia/Tehran  

  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3    
    restart: on-failure   
    environment:
      - node.name=elasticsearch-master
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-slave
      - cluster.initial_master_nodes=elasticsearch-master,elasticsearch-slave
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1      
    volumes:
      - elasticsearch-master-data:/usr/share/elasticsearch/data    
    ports:
      - 9200:9200
    networks:
      - elastic    

  elasticsearch-slave:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3        
    restart: on-failure   
    environment:
      - node.name=elasticsearch-master
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-master
      - cluster.initial_master_nodes=elasticsearch-master,elasticsearch-slave
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-slave-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    deploy: 
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    restart: on-failure 
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: 0.0.0.0
      SERVER_PORT: 5601
      ELASTICSEARCH_URL: http://elasticsearch-master:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-master:9200", "http://elasticsearch-slave:9200"]'
    networks:
      - elastic